#!/usr/bin/env python3
"""WitnessONE field-edition builder.  MG
Reads versioned device templates from templates/*.json, generates the embedded
registry module, and concatenates src/app into dist/WitnessONE.html — a single
offline file. The same templates are served live by the WitnessONE Agent."""
import json, glob, os, datetime

ROOT = os.path.dirname(os.path.abspath(__file__))
ORDER = ['01_head.html', '02_body.html', '04_three_lib.html', '03_registry.js',
         '04b_registry.js', '05_sim.js', '05b_live.js', '06_scene.js',
         '07_ui.js', '08_test.js', '09_report.js', '09b_help.js', '09c_flow.js',
         '10_boot.js', '11_tail.html']

def gen_registry():
    # v2 layout: devices/*.json (identity) + pointslists/<dev>/*.json (SPL REVISIONS —
    # selectable: a device can be witnessed against v4.17 … or SPL 1.0)
    devs, lists = [], {}
    for p in sorted(glob.glob(os.path.join(ROOT, 'devices', '*.json'))):
        d = json.load(open(p))
        assert d.get('schema', '').startswith('witnessone.device/'), f'bad schema in {p}'
        devs.append(d)
    for d in devs:
        revs = []
        for p in sorted(glob.glob(os.path.join(ROOT, 'pointslists', d['id'], '*.json'))):
            r = json.load(open(p))
            assert r.get('schema', '').startswith('witnessone.pointslist/'), f'bad schema in {p}'
            assert r['spl']['points'], f'no points in {p}'
            revs.append(r)
        # approved first, then drafts; newest label last wins nothing — stable by file order
        revs.sort(key=lambda r: (r.get('status') != 'approved', r.get('revId','')))
        assert revs, f"device {d['id']} has no points-list revisions"
        # Forward drift guard (DATA-7): if a device declares an expected point
        # count, the approved revision must still match it — catches curated
        # sets silently gaining/losing points on regeneration.
        exp = (d.get('registry') or {}).get('pointCount')
        if exp is not None:
            appr = next((r for r in revs if r.get('status') == 'approved'), revs[0])
            npts = len(appr['spl']['points'])
            assert npts == exp, (f"{d['id']}: approved revision has {npts} points but device "
                                 f"registry.pointCount declares {exp}")
        lists[d['id']] = revs
    devs.sort(key=lambda d: (d['id'] != 'vertiv-xdu1350b-cdu', d['identity']['make']))
    # Inline-<script> hardening (BP-1): vendor free-text fields are embedded
    # verbatim; escape '</' so a value like '</script>' cannot terminate the
    # script element early and break the whole offline app.
    def sj(obj):
        return json.dumps(obj).replace('</', '<\\/')
    js = ('<script>\n/* GENERATED by build.py — embedded registry v2: devices + SPL revisions */\n'
          f'window.W1_REGISTRY_EMBEDDED={{version:"embedded-v2",generated:"{datetime.date.today()}",'
          f'devices:{sj(devs)},pointslists:{sj(lists)}}};\n'
          '(function(){const E=window.W1_REGISTRY_EMBEDDED;const d=E.devices[0];\n'
          ' const rl=E.pointslists[d.id];const rev=rl.find(r=>r.revId===d.defaultPointsList)||rl[0];\n'
          ' window.W1_ACTIVE_TEMPLATE={schema:"witnessone.device-template/1",id:d.id,class:d.class,\n'
          '   identity:d.identity,layout:d.layout,fwtScript:d.fwtScript,\n'
          '   registry:Object.assign({},d.registry,{splVersion:rev.splVersion,revId:rev.revId,revStatus:rev.status}),\n'
          '   spl:rev.spl};\n'
          ' window.SPL_DB={points:rev.spl.points.slice(),meta:rev.spl.meta,stateTables:rev.spl.stateTables,revlog:rev.spl.revlog};\n'
          ' window.W1_ACTIVE_TEMPLATE.spl=window.SPL_DB;})();\n</script>\n')
    open(os.path.join(ROOT, 'src', 'app', '03_registry.js'), 'w').write(js)
    return len(devs), sum(len(v) for v in lists.values())

def build():
    nd, nr = gen_registry()
    out = ''.join(open(os.path.join(ROOT, 'src', 'app', f)).read() for f in ORDER)
    os.makedirs(os.path.join(ROOT, 'dist'), exist_ok=True)
    open(os.path.join(ROOT, 'dist', 'WitnessONE.html'), 'w').write(out)
    print(f'built dist/WitnessONE.html · {len(out)} bytes · {nd} device(s) · {nr} points-list revision(s)')

if __name__ == '__main__':
    build()
